environment:
  matrix:
    - platform: x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      generator: "MinGW Makefiles"
      compiler: mingw
      toolchain: 'C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin'
      configuration: Release

    - platform: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      generator: "MinGW Makefiles"
      compiler: mingw
      toolchain: 'C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin'
      configuration: Release

matrix:
  fast_finish: false

init:
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  - cmd: reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" /t REG_DWORD /f /v "AllowDevelopmentWithoutDevLicense" /d "1"
  - cmd: ren "C:\Program Files\Git\usr\bin\sh.exe" _sh.exe

build_script:
  - mkdir build
  - cd build
  - if [%compiler%]==[msvc] cmake -G"%generator%" ..
  - if [%compiler%]==[mingw] set PATH=%toolchain%\bin;%PATH%
  - if [%compiler%]==[mingw] cmake -G"%generator%" -DCMAKE_SH=CMAKE_SH-NOTFOUND -DCMAKE_BUILD_TYPE=%configuration% ..
  - cmake --build . --config %configuration%
  
test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - set CTEST_OUTPUT_ON_FAILURE=1
  - ctest -C %configuration% 
  - cd ..

